#!/bin/sh

strings | \
  # Subshell loop to omit everything before CNSL
  # Because sometimes LEAD and other values are in BIC and throw my analysis off
  # Wow, this really, really slows this script down
  (
    while read line
    do
      #printf "%s\n" $line
      echo $line
    done
  ) | \
  # Omit strings 9 chars or longer
  grep -vE '.{9}' | \
  # Match headers, return only matched characters (so e.g. TILE$ isn't separate from TILE)
  grep -oE '^[A-Z ]{3}[A-Z0-9# ]' | \
  # Need to sort before uniq
  sort | \
  # Show counts of uniqe values
  uniq -c | \
  # Sort the results, largest counts last
  sort
