package civ3satgql

import (
	"encoding/json"
	"log"
	"net/http"
	"strconv"

	"github.com/graphql-go/graphql"
	"github.com/graphql-go/handler"
	"github.com/myjimnelson/c3sat/parseciv3"
)

type sectionType struct {
	name   string
	offset int
	length int
}

type saveGameType struct {
	path     string
	data     []byte
	sections []sectionType
}

var saveGame saveGameType

// populates the structure given a path to a sav file
func (sav *saveGameType) loadSave(path string) error {
	var i, count, offset int
	var err error
	sav.data, _, err = parseciv3.ReadFile(path)
	if err != nil {
		return err
	}
	sav.path = path
	// find sections demarc'ed by 4-character ASCII headers
	for i < len(sav.data) {
		if sav.data[i] < 0x20 || sav.data[i] > 0x5a {
			count = 0
		} else {
			if count == 0 {
				offset = i
			}
			count++
		}
		i++
		if count > 3 {
			count = 0
			s := new(sectionType)
			s.offset = offset
			s.name = string(sav.data[offset:i])
			sav.sections = append(sav.sections, *s)
		}
	}
	return nil
}

// returns just the filename part of the path assuming / or \ separators
func (sav *saveGameType) fileName() string {
	var o int
	for i := 0; i < len(sav.path); i++ {
		if sav.path[i] == 0x2f || sav.path[i] == 0x5c {
			o = i
		}
	}
	return sav.path[o+1:]
}

// Handler wrapper to allow adding headers to all responses
// concept yoinked from http://echorand.me/dissecting-golangs-handlerfunc-handle-and-defaultservemux.html
func setHeaders(handler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Set Origin headers for CORS
		// yoinked from http://stackoverflow.com/questions/12830095/setting-http-headers-in-golang Matt Bucci's answer
		if origin := r.Header.Get("Origin"); origin != "" {
			w.Header().Set("Access-Control-Allow-Origin", origin)
			w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
			w.Header().Set("Access-Control-Allow-Headers",
				"Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		}
		// Since we're dynamically setting origin, don't let it get cached
		w.Header().Set("Vary", "Origin")
		handler.ServeHTTP(w, r)
	})
}

func Server(path string, bindAddress, bindPort string) error {
	saveGame.loadSave(path)

	Schema, err := graphql.NewSchema(graphql.SchemaConfig{
		Query: queryType,
		// Mutation: MutationType,
	})
	if err != nil {
		return err
	}

	// create a graphl-go HTTP handler
	graphQlHandler := handler.New(&handler.Config{
		Schema: &Schema,
		Pretty: false,
		// GraphiQL provides simple web browser query interface pulled from Internet
		GraphiQL: false,
		// Playground provides fancier web browser query interface pulled from Internet
		Playground: true,
	})

	http.Handle("/graphql", setHeaders(graphQlHandler))
	log.Fatal(http.ListenAndServe(bindAddress+":"+bindPort, nil))
	return nil
}

func Query(query, path string) (string, error) {
	saveGame.loadSave(path)
	Schema, err := graphql.NewSchema(graphql.SchemaConfig{
		Query: queryType,
		// Mutation: MutationType,
	})
	if err != nil {
		return "", err
	}
	result := graphql.Do(graphql.Params{
		Schema:        Schema,
		RequestString: query,
	})
	out, err := json.Marshal(result)
	if err != nil {
		return "", err
	}

	// return hex.EncodeToString(saveGame[:4]), nil
	return string(out[:]), nil
}

// Adapting this from the parseciv3 module to pull data this module's way
//   To keep the existing seed command without having to gql everything
// WorldSettings Returns the information needed to regenerate the map
// presuming the map was originally generated by Civ3 and not later edited
func WorldSettings(path string) ([][3]string, error) {
	var worldSize = [...]string{"Tiny", "Small", "Standard", "Large", "Huge", "Random"}
	// // "No Barbarians" is actually -1. To make code simpler, add one to value for array index
	var barbs = [...]string{"No Barbarians", "Sedentary", "Roaming", "Restless", "Raging", "Random"}
	var landMass = [...]string{"Archipelago", "Continents", "Pangea", "Random"}
	var oceanCoverage = [...]string{"80% Water", "70% Water", "60% Water", "Random"}
	var climate = [...]string{"Arid", "Normal", "Wet", "Random"}
	var temperature = [...]string{"Warm", "Temperate", "Cool", "Random"}
	var age = [...]string{"3 Billion", "4 Billion", "5 Billion", "Random"}
	var settings [][3]string
	saveGame.loadSave(path)
	wrldSection, err := SectionOffset("WRLD", 1)
	if err != nil {
		return [][3]string{}, err
	}
	settings = [][3]string{
		{"Setting", "Choice", "Result"},
		{"World Seed", strconv.FormatUint(uint64(ReadInt32(wrldSection+170, Signed)), 10), ""},
		{"World Size", worldSize[ReadInt32(wrldSection+234, Signed)], ""},
		{"Barbarians", barbs[ReadInt32(wrldSection+194, Signed)+1], barbs[ReadInt32(wrldSection+198, Signed)+1]},
		{"Land Mass", landMass[ReadInt32(wrldSection+202, Signed)], landMass[ReadInt32(wrldSection+206, Signed)]},
		{"Water Coverage", oceanCoverage[ReadInt32(wrldSection+210, Signed)], oceanCoverage[ReadInt32(wrldSection+214, Signed)]},
		{"Climate", climate[ReadInt32(wrldSection+186, Signed)], climate[ReadInt32(wrldSection+190, Signed)]},
		{"Temperature", temperature[ReadInt32(wrldSection+218, Signed)], temperature[ReadInt32(wrldSection+222, Signed)]},
		{"Age", age[ReadInt32(wrldSection+226, Signed)], age[ReadInt32(wrldSection+230, Signed)]},
	}
	return settings, nil
}
